language: python
python:
  - '3.6'
addons:
  chrome: stable
install:
  - pip install -r tests/requirements-test.txt
  - pip install -r requirements.txt
script:
  - python setup.py install
  - pytest -n 15 --cov=./scylla tests
after_success:
  - codecov